// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package sqlite

import (
	"database/sql"
)

type Gamer struct {
	ID        int64  `json:"id"`
	UserName  string `json:"user_name"`
	StartDate int64  `json:"start_date"`
	EndDate   int64  `json:"end_date"`
	Target    int64  `json:"target"`
}

type RawActivity struct {
	ID           int64          `json:"id"`
	UserID       int64          `json:"user_id"`
	CreateAt     int64          `json:"create_at"`
	StartDate    int64          `json:"start_date"`
	Distance     float64        `json:"distance"`
	AverageSpeed float64        `json:"average_speed"`
	MovingTime   int64          `json:"moving_time"`
	Name         sql.NullString `json:"name"`
	SportType    string         `json:"sport_type"`
	MaxSpeed     float64        `json:"max_speed"`
	OriginalData sql.NullString `json:"original_data"`
}

type RegisterUser struct {
	ID            int64         `json:"id"`
	UserName      string        `json:"user_name"`
	ProfileMedium string        `json:"profile_medium"`
	Profile       string        `json:"profile"`
	AccessToken   string        `json:"access_token"`
	RefreshToken  string        `json:"refresh_token"`
	ExpiredAt     int64         `json:"expired_at"`
	Active        sql.NullInt64 `json:"active"`
}
