// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package sqlite

import (
	"context"
)

type Querier interface {
	CreateActivity(ctx context.Context, arg CreateActivityParams) error
	CreateChallenge(ctx context.Context, arg CreateChallengeParams) (Challenge, error)
	CreateGamer(ctx context.Context, arg CreateGamerParams) (Gamer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (int64, error)
	DeleteGamer(ctx context.Context, arg DeleteGamerParams) error
	DisableUser(ctx context.Context, arg DisableUserParams) (int64, error)
	GetActiveUser(ctx context.Context, id int64) (GetActiveUserRow, error)
	GetActivity(ctx context.Context, arg GetActivityParams) ([]GetActivityRow, error)
	GetChallenge(ctx context.Context, id int64) (Challenge, error)
	GetLongestActivityPerDay(ctx context.Context, challengeID int64) ([]RawActivity, error)
	GetToken(ctx context.Context, id int64) (GetTokenRow, error)
	IsActiveUser(ctx context.Context, id int64) (int64, error)
	ListActiveUsers(ctx context.Context) ([]int64, error)
	ListChallenge(ctx context.Context) ([]Challenge, error)
	ListGamers(ctx context.Context, challengeID int64) ([]ListGamersRow, error)
	UpdateChallenge(ctx context.Context, arg UpdateChallengeParams) (Challenge, error)
	UpdateToken(ctx context.Context, arg UpdateTokenParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
